name: CI

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  html-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          css: true

      - name: Check links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --no-progress --exclude-mail '*.html'
          fail: true
